# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-29 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='borda_price',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='config',
            name='frete',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='config',
            name='year',
            field=models.IntegerField(default=2021),
        ),
    ]
