# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-02-02 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210129_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recheio', models.CharField(max_length=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.AlterModelOptions(
            name='config',
            options={'verbose_name': 'Configuration'},
        ),
        migrations.AlterField(
            model_name='config',
            name='site_name',
            field=models.CharField(default='Hello Pizza', max_length=255),
        ),
    ]
