# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-02-03 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210202_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='phone',
            field=models.CharField(default='5512981246322', max_length=13),
        ),
    ]
